version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nfty-feed-postgres
    environment:
      POSTGRES_DB: nfty-feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lobcity1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  postgres_data: